# Service Teleporter configuration example for L2J game server.

services:
  l2j-server-game:
    environment:
      - L2JFILES_SERVICE_TELEPORTER=service/teleporter/json/global.json,service/teleporter/json/voiced.json
    env_file:
      - server/custom/service-teleporter/.env
